### ISSUE TITLE
asset.resx内ウィンドウ表示条件のスキーマについて

### ISSUE THREAD

**Issue by FoxRefire** [Misaki0331/Win-kurarin#1]
こんにちは。
現在このプロジェクトをクロスプラットフォームでElectron、ブラウザで実行できるようにHTML/Javascriptにポートしようと試みています。
https://github.com/FoxRefire/kyukurarin.js
https://foxrefire.github.io/kyukurarin.js/

そこで技術的に容易であれば、このプロジェクトに含まれるasset.resx内の表示ルールを現在開発中の実装で利用できる形式に変換して流用したいと考えていますが大丈夫でしょうか？
可能であれば当該ファイル内の表示条件がどういったスキーマで記述されているのか解説いただければ幸いです。

尚、私が移植を試みているHTML/Javascriptによる実装では必要があれば都度変更する予定ですが、[kit.js](https://github.com/FoxRefire/kyukurarin.js/blob/main/kit.js)内で定義したウィンドウの開閉、移動を行う関数をinit処理が終了した後、[anim.js](https://github.com/FoxRefire/kyukurarin.js/blob/main/anim.js)から呼び出すことで行おうと考えています。

**Comment by Misaki0331** [comment]
基本的に問題ありません。自由に使っていただいて大丈夫です。


リソースの内容のフォーマットは以下の通りになります。

また、本編で扱う内部サイズは854x480であり、解像度に応じてスケーリングされます。
内部座標0,0は画面の中心(左上から427,240)です。


# オブジェクトの初期設定
``Sprite,レイヤー位置,画像のアンカー,ファイル名,初期横幅サイズ(0=320),初期縦幅サイズ(0=240)``
今回、レイヤーやアンカーは固定です。


# オブジェクトの表示設定
`` 種類,イージング種類,開始時間(ms),終了時間(ms),開始位置,終了位置`` 
アニメーション移動が可能になります。

`` 種類,0,イベント時間(ms),,指定位置``
指定した位置に一瞬で移動します。

種類は以下の通り
* ``MX`` : X座標の移動
* ``MY`` : Y座標の移動
* ``M`` : XY座標の移動(以下参照)
* ``F`` : 透明度の設定(値は0(非表示)～1(表示))
* ``S`` : 拡大率の設定(基本的に1がデフォルト)
* ``R`` : (今回はありませんが)回転の設定など

Mの場合直線でアニメーション移動する場合は
`` M,0,開始時間(ms),終了時間(ms),開始位置X,開始位置Y,終了位置X,終了位置Y``
指定した位置に瞬間移動させる場合は
`` M,0,イベント時間(ms),,指定位置X,指定位置Y``

また、オブジェクトは下に行くにつれて優先的に前面表示されるようになります。

**Comment by FoxRefire** [comment]
ありがとうございます。参考にさせていただきます。
